### PR TITLE
fix: Apply ISP to improve code flexibility.

### PR DESCRIPTION
**Pull request by unional**
Change the logger type from `Logger` to simply `{ id: string }`.

This is what's need by the `ConsoleAppender` and reduce the unnecessary coupling between the `Appender` and the `Logger`.

This allows the `Appender` to improve and use independently of the `Logger`.

This change follows the Interface Segregation Principle to declare and consume only what you need.

As such, the `aurelia-logging` dependency is moved to devDependency.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Thanks @unional Makes good sense to me 😄 Can you amend this PR by removing the dist folder? We'll generate that when we build/release but generally don't want to include it in normal PRs. Thanks!

**Comment by unional** [comment]
Done. 🌷

**Comment by EisenbergEffect** [comment]
Oops! I'm really sorry @unional! I explaining things incorrectly. I didn't mean to have you remove the dist folder, but rather to remove your changes to the dist folder. In other words don't commit anything from the dist folder. Sorry for the confusion and the hassle! Do you think you can make that change?

**Comment by unional** [comment]
I see. Force pushed the change. 🌮

**Comment by EisenbergEffect** [comment]
Excellent. Thanks for your patience!

**Comment by unional** [comment]
No problem at all. Thanks for taking the PR. 🌷

**Pull request merged**
